name: Report a Bug
description: Use this template to report a bug.
title: "[Bug] "
labels: [ "bug" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a more detailed description of the bug.
      placeholder: Describe the bug in detail here.
    validations:
      required: true
